language: python

python:
  - "2.7"
  - "3.8"
 
install:
  - which python

#before_script:
#  - export PYTHONPATH="./src:./test:$PYTHONPATH"

script:
  - echo $PYTHONPATH
  - pwd
  - ls
  - python -u ./test/pcap2sipp_test.py