language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
 
install:
  - which python
  - pip install codecov
  - pip install pytest 
  - pip install pytest-cov==2.5
  - pip install mock
  - pip install IPy
  - pip install scapy
  - pip install testfixtures

script:
  - pytest --cov=./ ./tests/*_test.py
  - python setup.py test
  
after_success:
  - codecov