language: python

python:
  - "2.7"
  - "3.8"
 
install:
  - which python
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install mock
  - pip install IPy
  - pip install scapy

script:
  - pytest --cov=./ ./tests/*_test.py
  - python setup.py test
  
after_success:
  - codecov