language: python

python:
  - "2.7"
  - "3.8"
 
install:
  - which python
  - pip install --user codecov

after_success:
  - codecov

script:
  - python -u ./tests/pcap2sipp_test.py
  - python setup.py test